### ISSUE TITLE
Npm version not installable

### ISSUE THREAD

**Issue by karel-3d** [dashevo/dashcore-node#11]
When I install from `npm`, `npm install` throws an error.

It's because `scripts/` scripts are not executable.

Whole `bitcore-dash` installation fails because of this.

**Comment by runn1ng** [comment]
This seems to be fixed in master already, but not in the npm version.

**Comment by runn1ng** [comment]
Also, the file in npm version seems to have DOS/Windows line endings, so it doesn't run on linux

**Comment by runn1ng** [comment]
Also the file is not downloaded, since it's not there  with the given version :)

**Comment by fanatid** [comment]
@runn1ng same issues for me... I installed but found that process still not started because:
```
[2017-12-06T11:58:50.189Z] error: Error: spawn /home/ubuntu/.nvm/versions/node/v4.8.6/lib/node_modules/bitcore-node-dash/lib/scaffold/data/dashd ENOENT
```
this project totally is not usable compare to bitcoin/litecoin

also zmq bindings is not installed automatically =\

**Comment by fanatid** [comment]
okay, changed exec in config to `/home/ubuntu/.bitcore/data/dashd` and now insight started :)

**Comment by runn1ng** [comment]
We also had to update zmq to zeromq for this to work

**Comment by fanatid** [comment]
Hm, I did next (maybe will be helpful for somebody):
```js
npm install --ignore-scripts bitcore-node-dash
cd node_modules/bitcore-node-dash
chmod +x scripts/download
dos2unix scripts/download
vim script/download # change version to 0.12.2
npm install
rm node_modules/bitcore-lib-dash
cd node_modules/zmq
npm install
```

and all works :)

**Comment by zarulizham** [comment]
@fanatid where to change exec in config?

**Comment by shamoons** [comment]
Does this no longer need to be done because of the fix in the merge PR?

**Comment by nmarley** [comment]
We're removing the DashCore download entirely from this and making it a separate dependency.

This work should be done by early next week at the latest. If this is needed right now, please use the  `develop` branch of this repo.
