### ISSUE TITLE
Merging back changes from bitcore-node

### ISSUE THREAD

**Issue by KamuelaFranco** [dashevo/dashcore-node#31]
_From @karel-3d on November 3, 2016 13:47_

Can you please merge changes back from bitcore-node 3.1.3 (and publish the result to npm)?

I am developing MyTrezor, there is a bug fixed in bitcore-node 3.1.3 with mempool, that would help us if it was fixed.

_Copied from original issue: dashpay/bitcore-node-dash#5_

**Comment by KamuelaFranco** [comment]
_From @karel-3d on November 3, 2016 13:48_

(We are now adding dash support to mytrezor)

**Comment by KamuelaFranco** [comment]
_From @schinzelh on November 3, 2016 14:8_

I'l have a look at it.

**Comment by KamuelaFranco** [comment]
_From @schinzelh on November 3, 2016 14:26_

@snogcel I have rebased bitcore-node-dash to bitcore-node-3.1.3. Travis looks good, please release bitcore-node-dash-3.1.3 to npmjs

**Comment by KamuelaFranco** [comment]
_From @snogcel on November 3, 2016 15:2_

tnx flare, I've published bitcore-node-dash@3.1.3 to npmjs.

@runn1ng can you please confirm?

**Comment by KamuelaFranco** [comment]
_From @karel-3d on May 3, 2017 15:1_

Hello, sorry for ignoring this :(

master_3.1.3 really has the necessary fixes. However, the master_3.1.3 and master started to diverge when I look at it :/ can you please merge. Thanks a lot

Also - note that bitpay started ignoring bitcore development. Since we really needed fixes for segwit (probably not applicable on dash), we started having our own forks

https://github.com/satoshilabs?utf8=%E2%9C%93&q=insight&type=&language=
https://github.com/satoshilabs?utf8=%E2%9C%93&q=bitcore&type=&language=
https://github.com/satoshilabs/bitcoin (<-this is bitcore patchset rebased on latest bitcoin-core)
 
Right now I can't promise we will keep them maintained; for that reason we didn't add them to npm (so it doesn't seem like we are "promising" to maintain) and we are installing everything from github commits; we might change that in the future.

**Comment by nmarley** [comment]
Closed in original repo
