### ISSUE TITLE
OSX download

### ISSUE THREAD

**Issue by KamuelaFranco** [dashevo/dashcore-node#32]
_From @snogcel on February 17, 2017 1:40_

bitcore-node-dash is failing when attempting to retrieve OSX binaries, will get fixed soon (or disable automatic download for OSX)

_Copied from original issue: dashpay/bitcore-node-dash#11_

**Comment by KamuelaFranco** [comment]
_From @viest on August 19, 2017 1:51_

Yeah, it solved my problem.

**Comment by nmarley** [comment]
Closed in original repo
