### ISSUE TITLE
Lack of initial account address/tx information

### ISSUE THREAD

**Issue by KamuelaFranco** [dashevo/dashcore-node#34]
_From @bearxu83 on September 8, 2017 20:59_

For example, account address: Xo9UzA2B7yyEhsrQZyFPGCTuFbNGKgHkPU
tx: e0028eb9648db56b1ac77cf090b99048a8007e2bb64b68f092c03c7f56a662c7
 /insight-api-dash/txs/?block=00000000fa6cf7367e50ad14eb0ca4737131f256fc4c5841fd3c3f140140e6b6
will return 'Not Found'

Dash-insight showed no historical records about it.
But if use Dash block explorer, we can search it.

_Copied from original issue: dashpay/bitcore-node-dash#18_

**Comment by KamuelaFranco** [comment]
_From @Alex-Werner on September 11, 2017 15:51_

Hello @bearxu83 
Thank you very much for this issue, it's a very interesting bug !
Had a way to reproduce it for the account address, the transaction id. 
Concerning the block, it's because it's a block that doesn't exist on the Dash Blockchain (typo issue).

I do not know yet the reason of it, added as priority in the Sprint. 

I will get back to this issue very soon; Please don't hesitate to give me as much information about how you discovered the issue or if you have other existing cases you've found. 

If these are sensitive information, you can use my PGP here : keybase.io/awerner

**Comment by KamuelaFranco** [comment]
_From @nmarley on November 23, 2017 13:5_

Hi @bearxu83,

It looks like the txid you posted is actually the coinbase transaction/merkle root from the genesis block, which [doesn't actually exist](https://github.com/bitcoin/bitcoin/issues/3303#issuecomment-29157502) for all practical purposes.

It seems like this is [a known detail](https://www.dash.org/forum/threads/problem-about-showing-initial-accounts-transactions-info-in-dash-insight.16678/#post-138788) and not actually a bug.

**Comment by nmarley** [comment]
Closed in original repo
