### ISSUE TITLE
How to change checking processes

### ISSUE THREAD

**Issue by KamuelaFranco** [dashevo/dashcore-node#35]
_From @gitsad on November 9, 2017 13:0_

Hi,

First of all **it's not an issue**, it's more like a question.
We are trying to set up bitcore-node-dash to work with other cryptocurrency core. Lets say that everything in core is pretty much the same like in dash core so everything should work.

After resolving some problems we stuck on starting and exiting node process. It looks like this:
```
[2017-11-09T12:20:29.239Z] info: Using config: /Users/gitsad/GIT/bitcore-node-dash/ourcoinNode/bitcore-node-dash.json
[2017-11-09T12:20:29.241Z] info: Using network: testnet
[2017-11-09T12:20:29.242Z] info: Starting bitcoind
[2017-11-09T12:20:29.244Z] info: Using bitcoin config file: /Users/gitsad/GIT/bitcore-node-dash/ourcoinNode/data/dash.conf
[2017-11-09T12:20:29.249Z] info: Starting dash process
OurCoin Core server starting
[2017-11-09T12:20:29.294Z] warn: Dash process unexpectedly exited with code: 0
[2017-11-09T12:20:29.295Z] warn: Restarting dash child process in 5000ms
[2017-11-09T12:20:29.315Z] info: Dash Height: 0 Percentage: 0.01
[2017-11-09T12:20:29.324Z] info: Dash Daemon Ready
[2017-11-09T12:20:29.325Z] info: Starting web
[2017-11-09T12:20:29.369Z] info: Bitcore Node ready
[2017-11-09T12:20:29.802Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
[2017-11-09T12:20:29.802Z] info: ZMQ connected to: tcp://127.0.0.1:28332
```
Process exits and starts again:
```
[2017-11-09T12:20:34.301Z] info: Using bitcoin config file: /Users/gitsad/GIT/bitcore-node-dash/ourcoinNode/data/dash.conf
.
.
.
the same stuff
```

#### We found in lib code in `bitcore-node-dash/lib/services/bitcoind.js`

```
self.spawn.process.once('exit', function(code) {
      if (!self.node.stopping) {
        log.warn('Dash process unexpectedly exited with code:', code);
        log.warn('Restarting dash child process in ' + self.spawnRestartTime + 'ms');
        setTimeout(function() {
          self._spawnChildProcess(function(err) {
            if (err) {
              return self.emit('error', err);
            }
            log.warn('Dash process restarted');
          });
        }, self.spawnRestartTime);
      }
    });
```

We changed it by adding `return;` at the end of line:
```
self.spawn.process.once('exit', function(code) { return;
```

And this resolved our problem with the restarting process. 
### The question is:
Where can we find the conditions on which this function checks the process and how we can change it?

Every help will be appreciated. Thanks!

_Copied from original issue: dashpay/bitcore-node-dash#21_

**Comment by KamuelaFranco** [comment]
_From @Alex-Werner on November 9, 2017 22:3_

Hi ! 

I'm not sure that I get your question. The conditions on which this function check the process is here, by listening to the exit event. 
This event is triggered by the child_process module, see more about that here : https://nodejs.org/api/child_process.html#child_process_event_exit

Also want to mention that I would not recommend using the spawn feature, but instead manage the dashd process yourself and just connect to it using the config file. 
See more here : https://medium.com/@obusco/setup-instant-send-transaction-the-comprehensive-way-a80a8a0572e

**Comment by KamuelaFranco** [comment]
_From @gitsad on November 10, 2017 17:36_

Hi! Thanks for the response!

The instruction on medium does not solve our problem. However the first part of your response seems to be a clue for us 😄  . Ok, I understand that the `exit` event executes when `child process` ends. So my question is what is the `child process` in this case ? 

Is it this?:  `self.spawn.process = spawn(self.spawn.exec, options, {stdio: 'inherit'});`

And also the second question is if you know why this process ends? 🤔 

To be clear we are **not using dash core.** We are trying to set up bitcore-node-dash with other core which **is pretty the same as dash core**.

**Comment by KamuelaFranco** [comment]
_From @gitsad on November 10, 2017 19:29_

Does it matter if process of core has no `tty` ? When I start dash and list processes I have this line:
```
4004 ttys001    0:00.55 /Users/gitsad/GIT/dash/src/dashd --conf=/Volumes/PortableDisk/dash/dash.conf --datadir=/Volumes/PortableDisk/dash --testnet
```

But when I try to run my **_not dash core_**, I've got something like this:
```
4019 ??         0:00.11 /Users/gitsad/Downloads/futurocoin/_install/bin/ourcoind --conf=/Users/gitsad/GIT/bitcore-node-dash/ourCoinNode/data/dash.conf --datadir=/Users/gitsad/GIT/bitcore-node-dash/ourCoinNode/data --regtest
```

**Comment by KamuelaFranco** [comment]
_From @dpetrini on March 6, 2018 16:43_

Hi,
I solved, in my code, this issue: 

_We changed it by adding return; at the end of line:_

_self.spawn.process.once('exit', function(code) { return;_


Changing the node version, with nvm, to v4.

It seems spawn have different behaviors in different versions, in v4 works fine.

HIH

**Comment by nmarley** [comment]
Closed in original repo
