### ISSUE TITLE
Redirect bitcore-node-dash to dashevo repository

### ISSUE THREAD

**Issue by KamuelaFranco** [dashevo/dashcore-node#36]
_From @Alex-Werner on November 9, 2017 22:5_

Hey @UdjinM6 @nmarley 

Could we redirect to https://github.com/dashevo/bitcore-node-dash this repository :) 

(Same goes for other repository such as bitcore-lib-dash, insight-api-dash etc...)

_Copied from original issue: dashpay/bitcore-node-dash#22_

**Comment by KamuelaFranco** [comment]
_From @UdjinM6 on November 9, 2017 22:7_

I believe @schinzelh is the best to ask for repo transfer/redirect/whatever :)

**Comment by KamuelaFranco** [comment]
_From @nmarley on November 22, 2017 23:38_

For the Github links to work this way, we'll probably have to co-ordinate this in a specific order, e.g.:

1. Rename dashpay/bitcore-node-dash to dashpay/bitcore-node-dash.old (in order to retain history/issues/PRs, etc.)
2. Transfer dashevo/bitcore-node-dash to dashpay
3. Transfer dashpay/bitcore-node-dash _back_ to dashevo

... but I'll defer to @schinzelh as well on this.

**Comment by KamuelaFranco** [comment]
_From @nmarley on November 23, 2017 10:48_

Talked w/@schinzelh and he's ok w/this strategy, but unfortunately https://github.com/dashevo/bitcore-node-dash isn't a fork of this one (which is a bitpay fork), so if we try that then we'll lose the bitpay upstream link, which is something I believe we want to keep.

I'd recommend we do this instead:

1. first merge outstanding PR's in the dashevo repo
2. then PR from dashevo into here & merge

...at this point both versions will be in-sync.

3. remove the dashevo one
4. make a true fork into dashevo
5. finish the above strategy, which will make dashpay re-direct to dashevo as well as maintain the bitpay upstream link

**Comment by KamuelaFranco** [comment]
_From @nmarley on November 24, 2017 22:24_

Once we get all the issues/PR's resolved in this repo and codebases are synced, I will create the appropriate re-direct to dashevo.

**Comment by nmarley** [comment]
No need for duplicating this issue
