### ISSUE TITLE
Cannot install permission issue

### ISSUE THREAD

**Issue by KamuelaFranco** [dashevo/dashcore-node#37]
_From @zarulizham on November 24, 2017 4:46_

Hello, I cannot install this repo said that permission error. Please refer my question in Stackoverflow

https://stackoverflow.com/questions/47391205/npm-install-failed-due-to-permission-denied

_Copied from original issue: dashpay/bitcore-node-dash#23_

**Comment by KamuelaFranco** [comment]
_From @fanatid on December 6, 2017 12:0_

`scripts/download` is not executable
you should install with `--ignore-scripts`,
then `chmod +x ./scripts/download`
and `dos2unix ./scripts/download`

totally unusable package right now

**Comment by KamuelaFranco** [comment]
_From @zarulizham on December 7, 2017 1:26_

Thank you sir for your suggestions. I will try later on 😄

**Comment by KamuelaFranco** [comment]
_From @zarulizham on December 11, 2017 6:58_

Hi @fanatid, currently I already install `npm install -g bitcore-node-dash --ignore-scripts`, 

but when is it to `chmod +x ./scripts/download` and `dos2unix ./scripts/download`?

**Comment by KamuelaFranco** [comment]
_From @fanatid on December 11, 2017 7:7_

https://github.com/dashevo/bitcore-node-dash/issues/11#issuecomment-349661023

**Comment by KamuelaFranco** [comment]
_From @zarulizham on December 11, 2017 15:12_

Thanks for the URL. I am able to install without any error. But how to start the service?

I tried using `bitcore-node-dash start` but returns `bitcore-node-dash: command not found`

**Comment by KamuelaFranco** [comment]
_From @fanatid on December 11, 2017 15:19_

You should read all thread instead single comments.
https://github.com/dashevo/bitcore-node-dash/issues/11#issuecomment-349624619

**Comment by KamuelaFranco** [comment]
_From @zarulizham on December 12, 2017 3:36_

Alright I'm done with `bitcore-node-dash`. But when try to install `Insight UI Dash`, The command return error as below

<img width="515" alt="screen shot 2017-12-12 at 11 36 09 am" src="https://user-images.githubusercontent.com/10229855/33866290-acb83eae-df30-11e7-83b7-74d5d6f1f0d0.png">

**Comment by nmarley** [comment]
Closed in original repo
