### ISSUE TITLE
Export keys and move wallet

### ISSUE THREAD

**Issue by KamuelaFranco** [dashevo/dashcore-node#38]
_From @Serrenima on January 9, 2018 23:37_

I want clone wallet on my PC from server, I think is't not work with conflict?

Thanks.

_Copied from original issue: dashpay/bitcore-node-dash#24_

**Comment by KamuelaFranco** [comment]
_From @knoxcard on January 19, 2018 8:40_

Here is the dash-cli command line way to do it...

dash-cli dumpprivkey [dash-wallet-address]

**Example:**
dash-cli dumpprivkey Xr3eJquX3sKPaAxqvXDto1H9VYEgY8zygo

**Comment by KamuelaFranco** [comment]
_From @Serrenima on January 20, 2018 22:43_

I didn't want dump address key, I want dump wallet.

**Comment by nmarley** [comment]
Closed in original repo
