### ISSUE TITLE
Not in the npm registry

### ISSUE THREAD

**Issue by shamoons** [dashevo/dashcore-node#41]
```
npm ERR! Linux 4.4.0-124-generic
npm ERR! argv "/root/n/bin/node" "/root/n/bin/npm" "install" "-g" "@dashevo/dashcore-node"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! code E404

npm ERR! 404 Not found : @dashevo/dashcore-node
npm ERR! 404 
npm ERR! 404 '@dashevo/dashcore-node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

```

**Comment by Alex-Werner** [comment]
Hi ! Sorry for this disturbance, it's seems that we rushed the deprecation of this package sooner that we were able to. We forgot to release on npm the new update.
I initially plan to make another update in the next 2 days, but as I just heard about the issue, I will fixing that now by publishing the previous master release!

Sorry again, I'm on it now :)

**Comment by nmarley** [comment]
This is fixed now, verified npm install works. Closing.

**Comment by shamoons** [comment]
I don't see it on `npmjs.com`

**Comment by nmarley** [comment]
https://www.npmjs.com/package/@dashevo/dashcore-node

Should be here... can you not access that link?

**Comment by shamoons** [comment]
Ahhh - it didn't show up in search. Is this repo active? I see the name changed to `OLD`

**Comment by nmarley** [comment]
We want to keep the upstream link to the Bitpay parent thru GitHub, so had to do a bit of maintenance -- the current one should be here: https://github.com/dashevo/dashcore-node

**Comment by shamoons** [comment]
So this is the one that's `npm install`able?

**Comment by nmarley** [comment]
They are currently both the same as I synced the repos before migration. But all future development will take place in the repo I just linked above ^
